<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="renderer" content="webkit">
<meta name="applicable-device" content="pc,mobile">
<title>顽石视频-免费视频分享网站</title>
<meta name="keywords" content="免费视频 | mianfeishipin | 顽石视频 | 科幻电影 | 电视剧  " />
<meta name="description" content="" />
<link href="/duomiui/default/css/style.css" rel="stylesheet">
<script>var sitePath=''</script>
<script src="/duomiui/default/js/jquery-1.4.4.min.js"></script>
<script src="/duomiui/default/js/common.js"></script>
<script src="/duomiui/default/js/function.js"></script>
<script src="/duomiui/default/js/jquery.lazyload.js"></script>
<link href="/favicon.ico" type="image/x-icon" rel="icon">
<link href="/favicon.ico" type="image/x-icon" rel="shortcut icon">
<!--[if lt IE 9]>
<script src="/duomiui/default/js/html5shiv.min.js"></script>
<script src="/duomiui/default/js/respond.min.js"></script>
<![endif]-->
<script src="/duomiui/default/js/jquery.superslide.js" type="text/javascript"></script>
</head>
<body>
<div class="header-all">
  <div class="top clearfix">
    <ul class="logo"><a href="/"><img src="/duomiui/default/images/538db374906df88f.png" title="顽石视频"></a></ul>
    <ul class="top-nav">
      <li><a class="now" href="/">首页</a></li>
      
      
      <li class="" _t_nav="topnav-1"><a href="/list/?1.html">电影<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-2"><a href="/list/?2.html">电视剧<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-3"><a href="/list/?3.html">综艺<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      
      <li class="" _t_nav="topnav-4"><a href="/list/?4.html">动漫<i class="sjbgs"></i><i class="sjbgx"></i></a></li>
      
      
      <li><a href="/topic/?1.html">专题</a></li>
      <!--li class="" _t_nav="topnav-news"><a href="/news/">新闻<i class="sjbgs"></i><i class="sjbgx"></i></a></li-->
      <li><a href="/interface/gbook.php">留言</a></li>
    </ul>
    <ul class="search so">
      <form name="formsearch" id="formsearch" action='/search.php' method="post"  target="_self" autocomplete="off">
          <input class="input" name="searchword" type="text" id="keyword" placeholder="请输入影片或演员名" />
          <div class="so-key"><a href='/search.php?searchword=%E6%B5%B7%E8%B4%BC%E7%8E%8B'>海贼王</a> <a href='/search.php?searchword=%E5%A5%94%E8%B7%91%E5%90%A7%E5%85%84%E5%BC%9F'>奔跑吧兄弟</a> <a href='/search.php?searchword=%E5%A8%98%E4%BA%B2%E8%88%85%E5%A4%A7'>娘亲舅大</a> </div>
          <input class="imgbt" type="submit" value=""/>
      </form>
    </ul>
    <ul class="nav-qt aa">
      <li class="bb"><a href="javascript:void(0)" onMouseOver="$MH.showHistory(1);"><i class="jl"></i>观看历史</a>
      <div class="cc">
	  <script type="text/javascript" src="/duomiui/default/js/history.js"></script>
          <script type="text/javascript">$MH.limit=10;$MH.WriteHistoryBox(180,170,'font');$MH.recordHistory({name:'{playpage:name}',link:'{playpage:url}',pic:'{playpage:pic}'})</script></div>
      </li>
      <li class="bb"><strong class="ma"><i class="mabg"></i>手机观看</strong>
      <div class="cc maw"><img src="/duomiui/default/images/weixin.jpg" width="152" height="152"><p>扫描二维码用手机观看</p></div>  
      </li>
      <li class="bb member"><strong class="ma"><i class="mbbg"></i> 会员中心</strong>
        <div class="cc mbp">{duomicms:member}</div> 
      </li>
    </ul>
    <ul class="sj-search">
      <li class="sbtn2"><i class="sjbg-search"></i></li>
    </ul>
    <ul class="sj-nav">
      <li class="sbtn1"><i class="sjbg-nav"></i></li>
    </ul>
    <ul class="sj-navhome">
      <li><a href="/"><i class="sjbg-home"></i></a></li>
    </ul>  
  </div>
  <div class="nav-down clearfix">
  
  
  <div id="topnav-1" class="nav-down-1" style="display:none;" _t_nav="topnav-1">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/list/?5.html">动作片</a></li>
           
      <li><a href="/list/?6.html">喜剧片</a></li>
           
      <li><a href="/list/?7.html">爱情片</a></li>
           
      <li><a href="/list/?8.html">科幻片</a></li>
           
      <li><a href="/list/?9.html">剧情片</a></li>
           
      <li><a href="/list/?10.html">恐怖片</a></li>
           
      <li><a href="/list/?11.html">战争片</a></li>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-2" class="nav-down-1" style="display:none;" _t_nav="topnav-2">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/list/?12.html">大陆剧</a></li>
           
      <li><a href="/list/?13.html">港台剧</a></li>
           
      <li><a href="/list/?14.html">日韩剧</a></li>
           
      <li><a href="/list/?15.html">欧美剧</a></li>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-3" class="nav-down-1" style="display:none;" _t_nav="topnav-3">
    <div class="nav-down-2 clearfix">
    <ul>
      
    </ul>
    </div>
  </div>
  
  
  
  <div id="topnav-4" class="nav-down-1" style="display:none;" _t_nav="topnav-4">
    <div class="nav-down-2 clearfix">
    <ul>
      
    </ul>
    </div>
  </div>
  
  
  <div id="topnav-news" class="nav-down-1" style="display:none;" _t_nav="topnav-news">
    <div class="nav-down-2 clearfix">
    <ul>
           
      <li><a href="/articlelist/?16.html">影视资讯</a></li>
           
      <li><a href="/articlelist/?17.html">剧情介绍</a></li>
      
    </ul>
    </div>
  </div>
  <div id="sj-nav-1" class="nav-down-1 sy1 sj-noover" style="display:none;" _s_nav="sj-nav-1">
    <div class="nav-down-2 sj-nav-down-2 clearfix">
    <ul> 
      <li><a href="/">首页</a></li>
        
      <li><a href="/list/?1.html">电影</a></li>
        
      <li><a href="/list/?2.html">电视剧</a></li>
        
      <li><a href="/list/?3.html">综艺</a></li>
        
      <li><a href="/list/?4.html">动漫</a></li>
        
      <li><a href="/list/?5.html">动作片</a></li>
        
      <li><a href="/list/?6.html">喜剧片</a></li>
        
      <li><a href="/list/?7.html">爱情片</a></li>
        
      <li><a href="/list/?8.html">科幻片</a></li>
        
      <li><a href="/list/?9.html">剧情片</a></li>
        
      <li><a href="/list/?10.html">恐怖片</a></li>
        
      <li><a href="/list/?11.html">战争片</a></li>
        
      <li><a href="/list/?12.html">大陆剧</a></li>
        
      <li><a href="/list/?13.html">港台剧</a></li>
        
      <li><a href="/list/?14.html">日韩剧</a></li>
        
      <li><a href="/list/?15.html">欧美剧</a></li>
    
      <li><a href="/topic/?1.html">专题</a></li>
      <li><a href="/news/">新闻</a></li>
      <li><a href="/interface/gbook.php">留言</a></li>
    </ul>
    </div>
  </div>
  <div id="sj-nav-search" class="nav-down-1 sy2 sj-noover" style="display:none;" _t_nav1="sj-nav-search">
    <div class="nav-down-2 sj-nav-down-search clearfix">
    <form name="formsearch" id="formsearch" action='/search.php' method="post"  target="_self" autocomplete="off">
          <input class="input" name="searchword" type="text" id="keyword" placeholder="输入关键词"/>
          <input class="imgbt" type="submit" value="搜索"/>
      </form>
    </div>
  </div>
</div>
</div>
<!--div class="topone clearfix"></div-->
<div style="margin-top:30px"></div>
<div class="channel-focus">
  <div class="channel-silder layout">
    <ul class="channel-silder-cnt">
    
      <li class="channel-silder-panel"><a class="channel-silder-img" target="_blank" href="/detail/?112.html"><img src="/uploads/allimg/180513/1d70d970bff5fbd6.jpg" title="莽荒纪" /></a>
        <div class="channel-silder-intro">
          <div class="channel-silder-title">
            <h2><a target="_blank" href="/detail/?112.html" title="莽荒纪">莽荒纪</a></h2>
            <span>普通话</span></div>
          <ul class="channel-silder-info">
            <li class="long">
              <label>主演：</label>
              <span>刘恺威 王鸥 陈亦飞 张峻宁 牛骏峰 李威 赵予熙 张双利..</span></li>
            <li>类型：<span>电视剧</span></li>
            <li>导演：<span>黄祖权</span></li>
            <li>年份：<span>2018</span></li>
            <li>时间：<span>2018-05-07</span></li>
          </ul>
          <p class="channel-silder-desc"> 剧情：<span>盘古开天辟地直至三皇五帝之后，华夏大地诞生夏朝，在夏的疆域内，有一个叫做纪氏的古老家族，领主之子纪宁天赋秉然功夫超群。纪氏因发现矿脉而遭到一个叫雪龙山组织的觊觎，为了守护家族纪宁的父亲在战争中死去，纪...</span></p>
          <a class="channel-silder-play" target="_blank" href="/detail/?112.html" title="观看《莽荒纪》">马上观看</a></div>
      </li>
      
      <li class="channel-silder-panel"><a class="channel-silder-img" target="_blank" href="/detail/?145.html"><img src="/uploads/allimg/180513/de7ad1d3650bdbe2.jpg" title="厉害了，我的国" /></a>
        <div class="channel-silder-intro">
          <div class="channel-silder-title">
            <h2><a target="_blank" href="/detail/?145.html" title="厉害了，我的国">厉害了，我的国</a></h2>
            <span>华语</span></div>
          <ul class="channel-silder-info">
            <li class="long">
              <label>主演：</label>
              <span>周扬（配音演员）</span></li>
            <li>类型：<span>电影</span></li>
            <li>导演：<span>卫铁</span></li>
            <li>年份：<span>2018</span></li>
            <li>时间：<span>2018-05-07</span></li>
          </ul>
          <p class="channel-silder-desc"> 剧情：<span>本片以习近平新时代中国特色社会主义思想为内在逻辑，展示了在创新、协调、绿色、开放和共享的新发展理念下中国这五年的伟大成就，展现了中国人民在全面建设小康征程上的伟大奋斗，彰显了以习近平同志为核心的党中央的正确领导。凝聚起全党全国人民的磅礴力量，为实现中华民族伟大复兴的中国梦不断前进。 
中国共产党第十九次全国代表大会绘制了中国未来发展的宏伟蓝图，由中央电视台..</span></p>
          <a class="channel-silder-play" target="_blank" href="/detail/?145.html" title="观看《厉害了，我的国》">马上观看</a></div>
      </li>
      
      <li class="channel-silder-panel"><a class="channel-silder-img" target="_blank" href="/detail/?167.html"><img src="/uploads/allimg/180513/d7909862c28d952a.jpg" title="红海行动" /></a>
        <div class="channel-silder-intro">
          <div class="channel-silder-title">
            <h2><a target="_blank" href="/detail/?167.html" title="红海行动">红海行动</a></h2>
            <span>华语</span></div>
          <ul class="channel-silder-info">
            <li class="long">
              <label>主演：</label>
              <span>张译 黄景瑜 海清 杜江 张涵予</span></li>
            <li>类型：<span>电影</span></li>
            <li>导演：<span>林超贤</span></li>
            <li>年份：<span>2018</span></li>
            <li>时间：<span>2018-05-07</span></li>
          </ul>
          <p class="channel-silder-desc"> 剧情：<span>索马里海域外，中国商船遭遇劫持，船员全数沦为阶下囚。蛟龙突击队沉着应对，潜入商船进行突袭，成功解救全部人质。 
返航途中，非洲北部伊维亚共和国发生政变，恐怖组织连同叛军攻入首都， 当地华侨面临危险，海军战舰接到上级命令改变航向，前往执行撤侨任务。蛟龙突击队八人，整装待发。 
时间紧迫，在“撤侨遇袭可反击，相反则必须避免交火，以免引起外交冲突”的大原则下，海..</span></p>
          <a class="channel-silder-play" target="_blank" href="/detail/?167.html" title="观看《红海行动》">马上观看</a></div>
      </li>
      
      <li class="channel-silder-panel"><a class="channel-silder-img" target="_blank" href="/detail/?30650.html"><img src="/uploads/allimg/180526/a9e1e0fdc82b98ed.gif" title="跨界歌王 第三季" /></a>
        <div class="channel-silder-intro">
          <div class="channel-silder-title">
            <h2><a target="_blank" href="/detail/?30650.html" title="跨界歌王 第三季">跨界歌王 第三季</a></h2>
            <span>中国</span></div>
          <ul class="channel-silder-info">
            <li class="long">
              <label>主演：</label>
              <span></span></li>
            <li>类型：<span>综艺</span></li>
            <li>导演：<span></span></li>
            <li>年份：<span>2018</span></li>
            <li>时间：<span>2018-05-26</span></li>
          </ul>
          <p class="channel-silder-desc"> 剧情：<span>《跨界歌王》是一档现象级大型明星跨界音乐节目。节目旨在突破固有的娱乐边界，汇集了活跃在影视、娱乐等领域的众多重量级当红明星。他们在各自的领域成就斐然，却都曾拥有音乐的梦想。在《跨界歌王》的舞台上，他们将重拾音乐之梦，展现鲜为人知且令观众惊艳的音乐才华，争夺年度“跨界歌王”的殊荣。</span></p>
          <a class="channel-silder-play" target="_blank" href="/detail/?30650.html" title="观看《跨界歌王 第三季》">马上观看</a></div>
      </li>
      
      <li class="channel-silder-panel"><a class="channel-silder-img" target="_blank" href="/detail/?31050.html"><img src="/uploads/allimg/180530/ffb47a444b59474f.jpg" title="泡沫之夏" /></a>
        <div class="channel-silder-intro">
          <div class="channel-silder-title">
            <h2><a target="_blank" href="/detail/?31050.html" title="泡沫之夏">泡沫之夏</a></h2>
            <span>国语</span></div>
          <ul class="channel-silder-info">
            <li class="long">
              <label>主演：</label>
              <span>张雪迎 秦俊杰 黄圣池 袁子芸 李逸男 陈欣予 麦迪娜 黄..</span></li>
            <li>类型：<span>电视剧</span></li>
            <li>导演：<span>于中中</span></li>
            <li>年份：<span>2018</span></li>
            <li>时间：<span>2018-05-29</span></li>
          </ul>
          <p class="channel-silder-desc"> 剧情：<span>夏沫和洛熙都是孤儿，少年的他们在养父母家相识，因为童年留在内心的阴影，他们彼此充满戒备和防范。洛熙在夏沫和弟弟参加电视歌唱大赛遇到尴尬状况下为他们解围，两人终于开始不戒备对方，可是洛熙却也爱上夏沫......</span></p>
          <a class="channel-silder-play" target="_blank" href="/detail/?31050.html" title="观看《泡沫之夏》">马上观看</a></div>
      </li>
      
    </ul>
    <ul class="channel-silder-nav">
    
      <li><a target="_blank" href="/detail/?112.html" ><img class="lazy" data-original="/uploads/allimg/180513/1d70d970bff5fbd6.jpg" src="../images/load.gif" alt="莽荒纪"></a></li>
      
      <li><a target="_blank" href="/detail/?145.html" ><img class="lazy" data-original="/uploads/allimg/180513/de7ad1d3650bdbe2.jpg" src="../images/load.gif" alt="厉害了，我的国"></a></li>
      
      <li><a target="_blank" href="/detail/?167.html" ><img class="lazy" data-original="/uploads/allimg/180513/d7909862c28d952a.jpg" src="../images/load.gif" alt="红海行动"></a></li>
      
      <li><a target="_blank" href="/detail/?30650.html" ><img class="lazy" data-original="/uploads/allimg/180526/a9e1e0fdc82b98ed.gif" src="../images/load.gif" alt="跨界歌王 第三季"></a></li>
      
      <li><a target="_blank" href="/detail/?31050.html" ><img class="lazy" data-original="/uploads/allimg/180530/ffb47a444b59474f.jpg" src="../images/load.gif" alt="泡沫之夏"></a></li>
      
    </ul>
  </div>
</div>
<script type="text/javascript">
	jQuery(".channel-silder").slide({ 
		titCell:".channel-silder-nav li",
		mainCell:".channel-silder-cnt",
		delayTime:800,
		triggerTime:0,
		interTime:5000,
		pnLoop:false,
		autoPage:false,
		autoPlay:true
	});
</script>
<div class="main">
<div style="margin-top:0"><br></div>
<table border="0" align="center" style="margin:0; margin: 5px auto; border: 1px solid #999; padding: 0 10px;  border-radius:5px;">
  <tr>
    <td width="22" height="22"><img src="/images/notice.png" width="22" height="22" /></td>
    <td width="1168"><strong>1. 需要新功能,或有bug,可在留言板留言.<br>2. 登录账号可查找播放记录.<br>3. 前几日由于更换解析接口导致大部分视频无法观看,目前已恢复正常,请各位用户放心观看.</strong></td>
  </tr>
</table>
</div>
<div class="main">
	<div class="index-area clearfix">
    <h1 class="title index-color">推荐影片</h1>
    <ul>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?16846.html" title="黑豹"><img class="lazy" data-original="/uploads/allimg/180517/102ecc033df0c66b.jpg" src="../images/load.gif" alt="黑豹"><span class="video-bg"></span><span class="lzbz"><p class="name">黑豹</p><p class="actor">查德维克·博斯曼 安迪·瑟金斯 露皮塔·尼永奥 迈克尔·B·乔丹 马丁·弗瑞曼</p><p class="actor">电影</p><p class="actor">2018/美国</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?164.html" title="航海王"><img class="lazy" data-original="/uploads/allimg/180513/fa104c98027c613c.jpg" src="../images/load.gif" alt="航海王"><span class="video-bg"></span><span class="lzbz"><p class="name">航海王</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">1999/日漫</p></span><p class="other"><i>838集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0"><a class="link-hover" href="/detail/?187.html" title="一人之下 第2季"><img class="lazy" data-original="/uploads/allimg/180513/0692bcd137e6a7a5.jpg" src="../images/load.gif" alt="一人之下 第2季"><span class="video-bg"></span><span class="lzbz"><p class="name">一人之下 第2季</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">2017/国漫</p></span><p class="other"><i>24集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?879.html" title="龙珠超"><img class="lazy" data-original="/uploads/allimg/180513/e14e26431a159ae7.jpg" src="../images/load.gif" alt="龙珠超"><span class="video-bg"></span><span class="lzbz"><p class="name">龙珠超</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">2015/日漫</p></span><p class="other"><i>131集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?20108.html" title="BLEACH 境·界"><img class="lazy" data-original="/uploads/allimg/180518/c2880f88e4eb338d.gif" src="../images/load.gif" alt="BLEACH 境·界"><span class="video-bg"></span><span class="lzbz"><p class="name">BLEACH 境·界</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">TV版/日本</p></span><p class="other"><i>366集</i></p></a>
    </li>
    
    </ul>
    </div>

	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/list/?5.html" class="on">动作片</a>
      
      <a href="/list/?6.html" class="on">喜剧片</a>
      
      <a href="/list/?7.html" class="on">爱情片</a>
      
      <a href="/list/?8.html" class="on">科幻片</a>
      
      <a href="/list/?9.html" class="on">剧情片</a>
      
      <a href="/list/?10.html" class="on">恐怖片</a>
      
      <a href="/list/?11.html" class="on">战争片</a>
      
      <a href="/list/?1.html">更多»</a>
      </span>
      电影</h1>
    <ul>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?16846.html" title="黑豹"><img class="lazy" data-original="/uploads/allimg/180517/102ecc033df0c66b.jpg" src="../images/load.gif" alt="黑豹"><span class="video-bg"></span><span class="lzbz"><p class="name">黑豹</p><p class="actor">查德维克·博斯曼 安迪·瑟金斯 露皮塔·尼永奥 迈克尔·B·乔丹 马丁·弗瑞曼</p><p class="actor">电影</p><p class="actor">2018/美国</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?279.html" title="少年透明人"><img class="lazy" data-original="/uploads/allimg/180513/945438c65e0c4e35.jpg" src="../images/load.gif" alt="少年透明人"><span class="video-bg"></span><span class="lzbz"><p class="name">少年透明人</p><p class="actor">卢多维科·吉拉尔代洛 诺亚·扎塔 瓦莱莉·高利诺</p><p class="actor">电影</p><p class="actor">2018/欧洲</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0"><a class="link-hover" href="/detail/?145.html" title="厉害了，我的国"><img class="lazy" data-original="/uploads/allimg/180513/de7ad1d3650bdbe2.jpg" src="../images/load.gif" alt="厉害了，我的国"><span class="video-bg"></span><span class="lzbz"><p class="name">厉害了，我的国</p><p class="actor">周扬（配音演员）</p><p class="actor">电影</p><p class="actor">2018/华语</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?3218.html" title="王牌保镖"><img class="lazy" data-original="/uploads/allimg/180513/5a92730a7b53b5b0.jpg" src="../images/load.gif" alt="王牌保镖"><span class="video-bg"></span><span class="lzbz"><p class="name">王牌保镖</p><p class="actor">瑞安·雷诺兹 塞缪尔·杰克逊 加里·奥德曼 萨尔玛·海耶克 艾洛蒂·袁 乔昆姆·德·阿尔梅达 克里斯蒂·米切尔 Joséphine de La Baume 山姆·哈兹尔丁 巴里·阿茨玛 Abbey Hoes Mikhail Gorevoy</p><p class="actor">电影</p><p class="actor">2018/美国</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?271.html" title="移动迷宫3：死亡解药"><img class="lazy" data-original="/uploads/allimg/180513/63705325e0cd7241.jpg" src="../images/load.gif" alt="移动迷宫3：死亡解药"><span class="video-bg"></span><span class="lzbz"><p class="name">移动迷宫3：死亡解药</p><p class="actor">迪伦·奥布莱恩 托马斯·桑斯特 李起弘 卡雅·斯考达里奥 吉安卡洛·埃斯珀西多</p><p class="actor">电影</p><p class="actor">2018/美国</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0 pmr0"><a class="link-hover" href="/detail/?76.html" title="头文字D"><img class="lazy" data-original="/uploads/allimg/180513/0e1985fd4a4b536e.jpg" src="../images/load.gif" alt="头文字D"><span class="video-bg"></span><span class="lzbz"><p class="name">头文字D</p><p class="actor">周杰伦 陈冠希 黄秋生 余文乐</p><p class="actor">电影</p><p class="actor">2018/华语</p></span><p class="other"><i>1集</i></p></a>
    </li>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/list/?12.html" class="on">大陆剧</a>
      
      <a href="/list/?13.html" class="on">港台剧</a>
      
      <a href="/list/?14.html" class="on">日韩剧</a>
      
      <a href="/list/?15.html" class="on">欧美剧</a>
      
      <a href="/list/?2.html">更多»</a>
      </span>
      电视剧</h1>
    <ul>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?30259.html" title="玄门大师"><img class="lazy" data-original="/uploads/allimg/180525/89ce2750727022e5.jpg" src="../images/load.gif" alt="玄门大师"><span class="video-bg"></span><span class="lzbz"><p class="name">玄门大师</p><p class="actor">佟梦实 王秀竹 裴子添 徐好 赵越 张雅卓 王佑硕 潘霜霜</p><p class="actor">电视剧</p><p class="actor">2018/内地</p></span><p class="other"><i>12集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?29714.html" title="微微一笑很倾城"><img class="lazy" data-original="/uploads/allimg/180524/6832f93fad2566f6.gif" src="../images/load.gif" alt="微微一笑很倾城"><span class="video-bg"></span><span class="lzbz"><p class="name">微微一笑很倾城</p><p class="actor">杨洋 郑爽 毛晓彤</p><p class="actor">电视剧</p><p class="actor">2015/中国</p></span><p class="other"><i>30集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0"><a class="link-hover" href="/detail/?25835.html" title="鹿鼎记"><img class="lazy" data-original="/uploads/allimg/180519/71ec6a436eee1d62.gif" src="../images/load.gif" alt="鹿鼎记"><span class="video-bg"></span><span class="lzbz"><p class="name">鹿鼎记</p><p class="actor">黄晓明 钟汉良 应采儿</p><p class="actor">电视剧</p><p class="actor">2008/中国</p></span><p class="other"><i>50集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?662.html" title="灵魂摆渡"><img class="lazy" data-original="/uploads/allimg/180513/b8a125a196472b2c.jpg" src="../images/load.gif" alt="灵魂摆渡"><span class="video-bg"></span><span class="lzbz"><p class="name">灵魂摆渡</p><p class="actor">刘智扬 于毅 肖茵 梁椰雯 小冉 杨逸飞 杜若溪 陈洁 刘芊含 满意</p><p class="actor">电视剧</p><p class="actor">2018/内地</p></span><p class="other"><i>20集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?615.html" title="真爱的谎言之破冰者"><img class="lazy" data-original="/uploads/allimg/180513/cadfbd2ade280e57.jpg" src="../images/load.gif" alt="真爱的谎言之破冰者"><span class="video-bg"></span><span class="lzbz"><p class="name">真爱的谎言之破冰者</p><p class="actor">罗晋 潘之琳 张晨光 曹征 吕星辰 王砚辉 程煜</p><p class="actor">电视剧</p><p class="actor">2018/内地</p></span><p class="other"><i>44集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0 pmr0"><a class="link-hover" href="/detail/?754.html" title="我的美女老师"><img class="lazy" data-original="/uploads/allimg/180513/9f0f2b40a8a49063.jpg" src="../images/load.gif" alt="我的美女老师"><span class="video-bg"></span><span class="lzbz"><p class="name">我的美女老师</p><p class="actor">张伦硕 杨子祯 王鑫尧 莫熙儿 宋乐 袁福福 王洁曦 李竹君</p><p class="actor">电视剧</p><p class="actor">2018/内地</p></span><p class="other"><i>35集</i></p></a>
    </li>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/list/?3.html">更多»</a>
      </span>
      综艺</h1>
    <ul>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?20048.html" title="幽默观察家"><img class="lazy" data-original="/uploads/allimg/180518/2fed0e0fb48c50ce.jpg" src="../images/load.gif" alt="幽默观察家"><span class="video-bg"></span><span class="lzbz"><p class="name">幽默观察家</p><p class="actor"></p><p class="actor">综艺</p><p class="actor">2018/内地</p></span><p class="other"><i>122集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?2429.html" title="星厨驾到第一季"><img class="lazy" data-original="/uploads/allimg/180513/5b40f98caf85f111.jpg" src="../images/load.gif" alt="星厨驾到第一季"><span class="video-bg"></span><span class="lzbz"><p class="name">星厨驾到第一季</p><p class="actor"></p><p class="actor">综艺</p><p class="actor">2018/内地</p></span><p class="other"><i>13集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0"><a class="link-hover" href="/detail/?1528.html" title="奔跑吧！伐木累"><img class="lazy" data-original="/uploads/allimg/180513/b6653a952ce6b2a6.jpg" src="../images/load.gif" alt="奔跑吧！伐木累"><span class="video-bg"></span><span class="lzbz"><p class="name">奔跑吧！伐木累</p><p class="actor"></p><p class="actor">综艺</p><p class="actor">2018/内地</p></span><p class="other"><i>17集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?2636.html" title="军情解码"><img class="lazy" data-original="/uploads/allimg/180513/0969829ae2b38c83.jpg" src="../images/load.gif" alt="军情解码"><span class="video-bg"></span><span class="lzbz"><p class="name">军情解码</p><p class="actor"></p><p class="actor">综艺</p><p class="actor">2018/内地</p></span><p class="other"><i>9集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?3646.html" title="高能少年团剧情升级版"><img class="lazy" data-original="/uploads/allimg/180513/4dd5f7c5408e4e27.jpg" src="../images/load.gif" alt="高能少年团剧情升级版"><span class="video-bg"></span><span class="lzbz"><p class="name">高能少年团剧情升级版</p><p class="actor"></p><p class="actor">综艺</p><p class="actor">2018/内地</p></span><p class="other"><i>3集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0 pmr0"><a class="link-hover" href="/detail/?28108.html" title="高能少年团第2季"><img class="lazy" data-original="/uploads/allimg/180520/f327c5a4b188b322.jpg" src="../images/load.gif" alt="高能少年团第2季"><span class="video-bg"></span><span class="lzbz"><p class="name">高能少年团第2季</p><p class="actor"></p><p class="actor">综艺</p><p class="actor">2018/内地</p></span><p class="other"><i>4集</i></p></a>
    </li>
    
    </ul>
    </div>
    
	<div class="index-area clearfix">
    <h1 class="title index-color">
       <span class="hitkey kp">
      
      <a href="/list/?4.html">更多»</a>
      </span>
      动漫</h1>
    <ul>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?879.html" title="龙珠超"><img class="lazy" data-original="/uploads/allimg/180513/e14e26431a159ae7.jpg" src="../images/load.gif" alt="龙珠超"><span class="video-bg"></span><span class="lzbz"><p class="name">龙珠超</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">2015/日漫</p></span><p class="other"><i>131集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?187.html" title="一人之下 第2季"><img class="lazy" data-original="/uploads/allimg/180513/0692bcd137e6a7a5.jpg" src="../images/load.gif" alt="一人之下 第2季"><span class="video-bg"></span><span class="lzbz"><p class="name">一人之下 第2季</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">2017/国漫</p></span><p class="other"><i>24集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0"><a class="link-hover" href="/detail/?164.html" title="航海王"><img class="lazy" data-original="/uploads/allimg/180513/fa104c98027c613c.jpg" src="../images/load.gif" alt="航海王"><span class="video-bg"></span><span class="lzbz"><p class="name">航海王</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">1999/日漫</p></span><p class="other"><i>838集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?20108.html" title="BLEACH 境·界"><img class="lazy" data-original="/uploads/allimg/180518/c2880f88e4eb338d.gif" src="../images/load.gif" alt="BLEACH 境·界"><span class="video-bg"></span><span class="lzbz"><p class="name">BLEACH 境·界</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">TV版/日本</p></span><p class="other"><i>366集</i></p></a>
    </li>
    
    <li class="p1 m1"><a class="link-hover" href="/detail/?1292.html" title="猎人×猎人"><img class="lazy" data-original="/uploads/allimg/180513/3af2b407ea96002a.jpg" src="../images/load.gif" alt="猎人×猎人"><span class="video-bg"></span><span class="lzbz"><p class="name">猎人×猎人</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">2011/日漫</p></span><p class="other"><i>148集</i></p></a>
    </li>
    
    <li class="p1 m1 mmr0 pmr0"><a class="link-hover" href="/detail/?409.html" title="画江湖之侠岚"><img class="lazy" data-original="/uploads/allimg/180513/285f6d25d120e543.jpg" src="../images/load.gif" alt="画江湖之侠岚"><span class="video-bg"></span><span class="lzbz"><p class="name">画江湖之侠岚</p><p class="actor"></p><p class="actor">动漫</p><p class="actor">2018/国漫</p></span><p class="other"><i>19集</i></p></a>
    </li>
    
    </ul>
    </div>
    
</div>
<div class="ylink clearfix">
    
</div>
<div class="footer clearfix">
<p>
本站不进行任何资源存储，只提供影视检索服务。若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢！<br>管理员Email：2904633401@qq.com
<br/>
 2018 <a style='margin-right: 5px;' href='/'>顽石视频</a><a href='http://www.miitbeian.gov.cn' target='_new'>渝ICP备17009334号</a>
</p>
</div>
<div class="gotop"><a class="gotopbg" href="javascript:;" title="返回顶部"></a></div>
<!--360自动提交页面-->
<script>(function(){
var src = (document.location.protocol == "http:") ? "http://js.passport.qihucdn.com/11.0.1.js?6a0110221179f6d143776803e0c69992":"https://jspassport.ssl.qhimg.com/11.0.1.js?6a0110221179f6d143776803e0c69992";
document.write('<script src="' + src + '" id="sozz"><\/script>');
})();
</script>


</body>
</html>